"use client";

import { 
  Zap, 
  Code2, 
  Clock,
  Github
} from "lucide-react";

export default function Variant2Page() {
  return (
    <div className="min-h-[calc(100vh-57px)] bg-black p-4 text-gray-400">
      <div className="grid grid-cols-4 grid-rows-3 gap-4 h-[800px]">
        {/* Large Hero Card */}
        <div className="col-span-2 row-span-2 bg-[#111] rounded-2xl p-6 border border-[#222] relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-6 opacity-50 group-hover:opacity-100 transition-opacity">
            <Zap className="w-6 h-6 text-yellow-500" />
          </div>
          <h3 className="text-sm font-medium uppercase tracking-widest text-gray-500 mb-2">Total Impact</h3>
          <p className="text-5xl font-bold text-white mb-4">$42,500</p>
          <p className="text-sm text-gray-500 max-w-[200px]">Estimated value generated by AI assistance this month.</p>
          
          <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-yellow-500/10 to-transparent" />
        </div>

        {/* Stat Cards */}
        <div className="col-span-1 bg-[#111] rounded-2xl p-6 border border-[#222] flex flex-col justify-between hover:border-blue-500/50 transition-colors">
          <div className="flex justify-between items-start">
            <h3 className="text-xs font-medium text-gray-500">Sessions</h3>
            <span className="text-xs font-bold bg-blue-500/20 text-blue-400 px-2 py-1 rounded-full">+12%</span>
          </div>
          <p className="text-3xl font-bold text-white">1,240</p>
        </div>

        <div className="col-span-1 bg-[#111] rounded-2xl p-6 border border-[#222] flex flex-col justify-between hover:border-purple-500/50 transition-colors">
          <div className="flex justify-between items-start">
            <h3 className="text-xs font-medium text-gray-500">Lines</h3>
            <span className="text-xs font-bold bg-purple-500/20 text-purple-400 px-2 py-1 rounded-full">+8%</span>
          </div>
          <p className="text-3xl font-bold text-white">84.2k</p>
        </div>

        {/* Wide Chart Card */}
        <div className="col-span-2 bg-[#111] rounded-2xl p-6 border border-[#222]">
          <h3 className="text-xs font-medium text-gray-500 mb-4">Activity Heatmap</h3>
          <div className="grid grid-cols-12 gap-1 h-32">
            {Array.from({ length: 48 }).map((_, i) => (
              <div 
                key={i} 
                className="rounded-sm"
                style={{ 
                  backgroundColor: `rgba(59, 130, 246, ${Math.random() * 0.8 + 0.1})` 
                }}
              />
            ))}
          </div>
        </div>

        {/* Tall List Card */}
        <div className="col-span-1 row-span-2 bg-[#111] rounded-2xl p-6 border border-[#222]">
          <h3 className="text-xs font-medium text-gray-500 mb-4">Recent Commits</h3>
          <div className="space-y-4">
            {[1, 2, 3, 4, 5, 6].map(i => (
              <div key={i} className="flex items-center gap-3">
                <Github className="w-4 h-4 text-gray-600" />
                <div className="flex-1 min-w-0">
                  <p className="text-sm text-gray-300 truncate">feat: Update dashboard UI</p>
                  <p className="text-[10px] text-gray-600">2m ago</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Small Detail Card */}
        <div className="col-span-1 bg-[#111] rounded-2xl p-6 border border-[#222] flex items-center gap-4">
          <div className="p-3 rounded-full bg-green-500/10 text-green-500">
            <Clock className="w-5 h-5" />
          </div>
          <div>
            <p className="text-2xl font-bold text-white">42h</p>
            <p className="text-xs text-gray-500">Saved</p>
          </div>
        </div>

        <div className="col-span-2 bg-[#111] rounded-2xl p-6 border border-[#222] flex items-center justify-center border-dashed">
          <span className="text-sm text-gray-600">Add Widget +</span>
        </div>
      </div>
    </div>
  );
}
